# Generated by Django 4.2.6 on 2023-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamada',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='equipe',
        ),
        migrations.AddField(
            model_name='obra',
            name='nome',
            field=models.CharField(default='Reforma', max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='equipe',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='lugar',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
