# Generated by Django 4.2.6 on 2023-10-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0002_remove_chamada_equipe_remove_obra_equipe_obra_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='nome',
            new_name='atividade',
        ),
    ]
